### ISSUE TITLE
Fix SimpleMDE styles in ShadyDOM

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-markdown#2]
For some reason Shady isn't applying its scoping to the dynamically injected SimpleMDE/CodeMirror DOM. This means that we can't style it. Not sure how to fix, or indeed what's going wrong.

/cc @bedeoverend

**Comment by bedeoverend** [comment]
Does shady work if you're not using Polymer's DOM methods? I believe the new Shady polyfill fixes this, by patching at a document level, but I thought that to make use of it, you had to do all your DOM manipulation through Polymer's helper methods, which obviously any external library wouldn't do.

**Comment by madeleineostoja** [comment]
The injected Dom is in the shadow root, so it should it shouldn't make a difference

**Comment by madeleineostoja** [comment]
This also messes with the new blur/click exit handlers for some reason
